
package com.vistas;

import com.conexion.Conexion;
import com.modelo.Usuarios;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *Nombre de la Clase: FrmLogin
 * Fecha: 18-08-19
 * Version:1.0
 * Copyright: ITCA-FEPADE
 * @author Francisco Hernandez
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        //rol();
    }
    FrmFacultad frmFacultad;
    FrmCarrera frmCarrera;
    FrmEstudiante frmEstu;
    FrmCrudUser frmUser;
    Creadores crea;
    public static int tipoUser;

    FrmPrincipal(Usuarios mod) {
        initComponents();
        setLocationRelativeTo(null);
        //rol();
        
    }
         
    public void rol(){
        if(FrmPrincipal.tipoUser==2){
            this.mUsuario.setVisible(false);
            this.mReporte.setVisible(false);
        }else{
            this.mUsuario.setVisible(true);
            this.mReporte.setVisible(true);
        }   
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mFacultad = new javax.swing.JMenu();
        mCarrera = new javax.swing.JMenu();
        mEstudiante = new javax.swing.JMenu();
        mUsuario = new javax.swing.JMenu();
        mReporte = new javax.swing.JMenu();
        rpt1 = new javax.swing.JMenuItem();
        rpt2 = new javax.swing.JMenuItem();
        rpt3 = new javax.swing.JMenuItem();
        rpt4 = new javax.swing.JMenuItem();
        rpt5 = new javax.swing.JMenuItem();
        rpt6 = new javax.swing.JMenuItem();
        mCreadores = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        mFacultad.setText("Facultad");
        mFacultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFacultadMouseClicked(evt);
            }
        });
        mFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFacultadActionPerformed(evt);
            }
        });
        jMenuBar1.add(mFacultad);

        mCarrera.setText("Carrera");
        mCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCarreraMouseClicked(evt);
            }
        });
        jMenuBar1.add(mCarrera);

        mEstudiante.setText("Estudiante");
        mEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEstudianteMouseClicked(evt);
            }
        });
        jMenuBar1.add(mEstudiante);

        mUsuario.setText("Usuario");
        mUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mUsuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(mUsuario);

        mReporte.setText("Reporte");

        rpt1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        rpt1.setText("Seleccionar Carrera");
        rpt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt1MouseClicked(evt);
            }
        });
        mReporte.add(rpt1);

        rpt2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        rpt2.setText("Buscar según Codigo");
        rpt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt2MouseClicked(evt);
            }
        });
        rpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt2ActionPerformed(evt);
            }
        });
        mReporte.add(rpt2);

        rpt3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        rpt3.setText("Seleccionar Facultad");
        rpt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt3MouseClicked(evt);
            }
        });
        mReporte.add(rpt3);

        rpt4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        rpt4.setText("Estudiante CUM Mayor");
        rpt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt4MouseClicked(evt);
            }
        });
        mReporte.add(rpt4);

        rpt5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        rpt5.setText("Carrera Mas Materias");
        rpt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt5MouseClicked(evt);
            }
        });
        mReporte.add(rpt5);

        rpt6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        rpt6.setText("Mayores de Edad");
        rpt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rpt6MouseClicked(evt);
            }
        });
        rpt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt6ActionPerformed(evt);
            }
        });
        mReporte.add(rpt6);

        jMenuBar1.add(mReporte);

        mCreadores.setText("Creadores");
        mCreadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCreadoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(mCreadores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFacultadActionPerformed
        
    }//GEN-LAST:event_mFacultadActionPerformed

    private void mFacultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFacultadMouseClicked
        if(frmFacultad == null){
            frmFacultad = new FrmFacultad();
            this.jDesktopPane1.add(frmFacultad);
            frmFacultad.setVisible(true);
        }else if(frmFacultad.isClosed()){
            frmFacultad = new FrmFacultad();
            this.jDesktopPane1.add(frmFacultad);
            frmFacultad.setVisible(true);
        }
        
    }//GEN-LAST:event_mFacultadMouseClicked

    private void mCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCarreraMouseClicked
        if(frmCarrera == null){
            try {
                frmCarrera = new FrmCarrera();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(frmCarrera);
            frmCarrera.setVisible(true);
        }else if(frmCarrera.isClosed()){
            try {
                frmCarrera = new FrmCarrera();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(frmCarrera);
            this.frmCarrera.setVisible(true);
        }
    }//GEN-LAST:event_mCarreraMouseClicked

    private void mEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEstudianteMouseClicked
        if(frmEstu == null){
            try {
                frmEstu = new FrmEstudiante();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(frmEstu);
            frmEstu.setVisible(true);
        }else if(frmEstu.isClosed()){
            try {
                frmCarrera = new FrmCarrera();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jDesktopPane1.add(frmEstu);
            this.frmEstu.setVisible(true);
        }
    }//GEN-LAST:event_mEstudianteMouseClicked

    private void mUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mUsuarioMouseClicked
      if(frmUser == null){
            frmUser = new FrmCrudUser();
            this.jDesktopPane1.add(frmUser);
            frmUser.setVisible(true);
        }else if(frmUser.isClosed()){
            frmUser = new FrmCrudUser();
            this.jDesktopPane1.add(frmUser);
            frmUser.setVisible(true);
        }
    }//GEN-LAST:event_mUsuarioMouseClicked

    private void mCreadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCreadoresMouseClicked
       if(crea == null){
            crea = new Creadores();
            this.jDesktopPane1.add(crea);
            crea.setVisible(true);
        }else if(crea.isClosed()){
            crea = new Creadores();
            this.jDesktopPane1.add(crea);
            crea.setVisible(true);
        }
    }//GEN-LAST:event_mCreadoresMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rol();
    }//GEN-LAST:event_formWindowOpened

    private void rpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpt2ActionPerformed

    private void rpt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt1MouseClicked

      
      Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/Carrera.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer.viewReport(jp,false);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
      
    }//GEN-LAST:event_rpt1MouseClicked

    private void rpt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt2MouseClicked
          Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/Codigo.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer.viewReport(jp,false);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
    }//GEN-LAST:event_rpt2MouseClicked

    private void rpt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt3MouseClicked
        Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/Facultad.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer.viewReport(jp,false);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
    }//GEN-LAST:event_rpt3MouseClicked

    private void rpt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt4MouseClicked
        Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/MaxCum.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer.viewReport(jp,false);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
    }//GEN-LAST:event_rpt4MouseClicked

    private void rpt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt5MouseClicked
        Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/MaxMateria.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer.viewReport(jp,false);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
    }//GEN-LAST:event_rpt5MouseClicked

    private void rpt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpt6ActionPerformed

    private void rpt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpt6MouseClicked
       Connection con=null;
     JasperReport repor;
     try 
     {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection(
                 "jdbc:mysql://localhost:3306/valladarespalaciosjocsantadeo",
                 "root","");
     } 
     catch (ClassNotFoundException | SQLException e) 
     {
         JOptionPane.showMessageDialog(null, e.getMessage());
     }
        
     try 
     {
         repor=JasperCompileManager.compileReport("src/com/reportes/MayorEdad.jrxml");
         JasperPrint jp=JasperFillManager.fillReport(repor,null,con);
         JasperViewer jv=new JasperViewer(jp);
         jv.setVisible(true);
         
     } 
     catch (JRException e) 
     {
         Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE,null,e);
     }
    }//GEN-LAST:event_rpt6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCarrera;
    private javax.swing.JMenu mCreadores;
    private javax.swing.JMenu mEstudiante;
    private javax.swing.JMenu mFacultad;
    private javax.swing.JMenu mReporte;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenuItem rpt1;
    private javax.swing.JMenuItem rpt2;
    private javax.swing.JMenuItem rpt3;
    private javax.swing.JMenuItem rpt4;
    private javax.swing.JMenuItem rpt5;
    private javax.swing.JMenuItem rpt6;
    // End of variables declaration//GEN-END:variables
}
